turn on the light
stand up
get dressing gown
put it on
open pocket
take the tablet
take the screwdriver and toothbrush
go south
get mail
south
lie down
wait
wait
wait
wait
wait
wait
south
west
wait
drink beer
drink beer
drink beer
buy cheese sandwich
east
give sandwich to the dog
north
wait
wait
take device
examine device
press green button
wait
wait
wait
wait
smell the dark
examine the shadow
eat the peanuts
