go east
take ball
nw
examine sundial
examine gnomon
unscrew gnomon and take it
ne
n
z
throw ball at the umbrella
take umbrella
w
w
open pram
push pram south
give coin too woman
give coin to woman
take bag and change
put coin in pocket
feed pigeons
take ruby
push pram east
examine boats
take paper bird and unfold it
examine paper
look at watch
push pram east
get in pram
open umbrella
get all
look at watch
